### ISSUE TITLE
Grouped groups by a semicolon

### ISSUE THREAD

**Issue by srobledog** [coreofscience/margaret_luisamigo#80]
there are duplicate groups in "Grupos individual en cifras"

![image](https://user-images.githubusercontent.com/8762305/132725816-0e3a6686-f310-4934-802d-dc19d9c275d8.png)

**Comment by bryanariasq02** [comment]
fixed problem with semicolon
![image](https://user-images.githubusercontent.com/64503849/133142701-30af43dc-526e-40fd-86ea-f05319e75433.png)

**Comment by srobledog** [comment]
@bryanariasq02 solved it
