### ISSUE TITLE
add more columns in investigadores

### ISSUE THREAD

**Issue by srobledog** [coreofscience/margaret_luisamigo#81]
add columns like this 

![image](https://user-images.githubusercontent.com/8762305/132963164-5ef55761-74c8-49a0-9c16-632d2f29781a.png)

plus events - total events. 

There is an example  in the branch unad (the last one)

**Comment by bryanariasq02** [comment]
![image](https://user-images.githubusercontent.com/64503849/134367816-4bb8ddd9-b5ec-4fc2-8268-99b10d7f6f0a.png)

**Comment by srobledog** [comment]
@bryanariasq02 solved it
