### ISSUE TITLE
add sede in investigadores

### ISSUE THREAD

**Issue by srobledog** [coreofscience/margaret_luisamigo#82]
We can add a column called sede in investigators, like this:

![image](https://user-images.githubusercontent.com/8762305/132963203-2cefe633-3429-47ab-a7d6-671ab10b7bf7.png)

it could get the data from a google sheet and merge it in the code... like the others

**Comment by bryanariasq02** [comment]
![image](https://user-images.githubusercontent.com/64503849/135452180-ef6e8642-cadd-4674-b432-13d3d288ad7b.png)
